name: 'Extract Python Package Version'
description: 'Extract version from setup.py, pyproject.toml, or __init__.py files'
branding:
  icon: 'package'
  color: 'blue'

inputs:
  file-path:
    description: 'Path to the file containing version (setup.py, pyproject.toml, __init__.py)'
    required: false
    default: 'auto'
  fallback-version:
    description: 'Fallback version if no version is found'
    required: false
    default: '0.0.0'

outputs:
  version:
    description: 'The extracted version number'
    value: ${{ steps.extract.outputs.version }}
  tag:
    description: 'The version with v prefix (e.g., v1.2.3)'
    value: ${{ steps.extract.outputs.tag }}
  major:
    description: 'Major version number'
    value: ${{ steps.extract.outputs.major }}
  minor:
    description: 'Minor version number'
    value: ${{ steps.extract.outputs.minor }}
  patch:
    description: 'Patch version number'
    value: ${{ steps.extract.outputs.patch }}

runs:
  using: 'composite'
  steps:
    - name: Extract version
      id: extract
      shell: bash
      run: |
        python3 ${{ github.action_path }}/extract_version.py \
          --file-path "${{ inputs.file-path }}" \
          --fallback-version "${{ inputs.fallback-version }}" \
          --output-file "$GITHUB_OUTPUT"